apiVersion: v1
kind: Secret
metadata:
  name: prestashop-secret
  namespace: prestashop
type: Opaque
data:
  mariadbpasswd: U3VwMzA2ODI2Lg== #Sup306826.
  prestashopdbname: cHJlc3Rhc2hvcDMwNjgyNg== #prestashop306826
  prestashopdbuser: ZGl5YW1h #diyama
  prestashopdbpasswd: U3VwMzA2ODI2Lg== #Sup306826.
  prestashopuserpasswd: U3VwMzA2ODI2Lg== #Sup306826.
