apiVersion: v1
kind: PersistentVolume
metadata:
  name: prestashop-pv-volume
  namespace: prestashop
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/psdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop-pv-claim
  namespace: prestashop
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
