apiVersion: v1
kind: Service
metadata:
  name: mariadb-prestashop
  namespace: prestashop
  labels:
    app: prestashop
spec:
  ports:
    - port: 3306
  selector:
    app: prestashop
    tier: mariadb
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mariadb-prestashop
  namespace: prestashop
spec:
  selector:
    matchLabels:
      app: prestashop
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prestashop
        tier: mariadb
    spec:
      containers:
      - image: bitnami/mariadb:10.1
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prestashop-secret
              key: mariadbpasswd    
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim